name: Quarterly Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      -  uses: ph-fritsche/action-dispatch@d2d2f5ace087c13e9d2ea162df1a7ba85730fb47 # v1
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           ident: cd.yaml
           payload: '{}'
